name: Update Romania railway

on:
  workflow_call:

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Install Ruby Deps
        run: sudo gem install nokogiri

      - name: Download Required files
        run: |
          wget https://data.gov.ro/dataset/b4e2ce0b-6935-44b1-8e9d-f3999123358a/resource/44d079a4-97d8-48c6-ab24-5ab454358245/download/s.c.-interregional-cltori-s.r.l_2025.xml -O data.gov.ro/s.c.-interregional-cltori-s.r.l_2025.xml 
          wget https://data.gov.ro/dataset/1da1018d-df38-4b5f-9667-88e4521abfb3/resource/b752e8bb-2701-4214-ba51-4a7948b2e217/download/s.c.-regio-calatori-s.r.l_271-trenuri_2025.xml -O data.gov.ro/s.c.-regio-calatori-s.r.l_271-trenuri_2025.xml
          wget https://data.gov.ro/dataset/1d057a43-3eaa-4fed-a349-4106f3ad0e49/resource/6eb9c474-235e-43bb-8d26-09fdb3fb8f6b/download/s.c.-astra-trans-carpatic-s.r.l_22-trenuri_2025.xml -O data.gov.ro/s.c.-astra-trans-carpatic-s.r.l_22-trenuri_2025.xml 
          wget https://data.gov.ro/dataset/9d4adc7b-d407-46c2-9003-5aa87cd16fb7/resource/c61db9e4-4bc3-4fb3-a9a2-7de49c68ad94/download/s.c.-transferoviar-calatori-srl_221-tr_2025.xml -O data.gov.ro/s.c.-transferoviar-calatori-srl_221-tr_2025.xml 
          wget https://data.gov.ro/dataset/e4ba7432-2904-4cc4-9588-2afbf021756e/resource/6c253786-b312-4d35-ad68-101a2b0b2858/download/s.c.-softrans-calatori-s.r.l_16-tr_2025.xml -O data.gov.ro/s.c.-softrans-calatori-s.r.l_16-tr_2025.xml
  
      - name: Run
        run: ruby parse.rb

      - name: Upload
        uses: stefanzweifel/git-auto-commit-action@v5
